name: image_recognization
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model.tflite
